table D_entreprise
	lineageTag: 64268d34-a21a-4fc2-8013-4564d5251291

	column id_entreprise
		dataType: int64
		formatString: 0
		lineageTag: be531c30-c0a4-4d6d-9b1f-8576d60f18c0
		summarizeBy: none
		sourceColumn: id_entreprise

		annotation SummarizationSetBy = Automatic

	column id_secteur
		dataType: int64
		formatString: 0
		lineageTag: fd6afc1f-7c24-4bc3-9d23-e4f04c95aa27
		summarizeBy: none
		sourceColumn: id_secteur

		annotation SummarizationSetBy = Automatic

	column nom_entreprise
		dataType: string
		lineageTag: bcce51ec-977b-4543-b103-dba7105244f1
		summarizeBy: none
		sourceColumn: nom_entreprise

		annotation SummarizationSetBy = Automatic

	column taille
		dataType: string
		lineageTag: fec3b12a-b778-40c2-b968-a49e1f4e93a3
		summarizeBy: none
		sourceColumn: taille

		annotation SummarizationSetBy = Automatic

	column categorie
		dataType: string
		lineageTag: 0a77be9d-274d-4cfc-a806-39992f67df8d
		summarizeBy: none
		sourceColumn: categorie

		annotation SummarizationSetBy = Automatic

	column siege_social
		dataType: string
		lineageTag: 5d17a537-8fe2-4745-8b5c-42651036700e
		summarizeBy: none
		sourceColumn: siege_social

		annotation SummarizationSetBy = Automatic

	column pays
		dataType: string
		lineageTag: 8da0c78e-bd27-43ce-b9b4-d16f01c998b6
		summarizeBy: none
		sourceColumn: pays

		annotation SummarizationSetBy = Automatic

	partition D_entreprise = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://univlyon2fr.sharepoint.com/sites/datalake_yea", [ApiVersion = 15]),
				    #"d_entreprise csv_https://univlyon2fr sharepoint com/sites/datalake_yea/Documents partages/Sources/" = Source{[Name="d_entreprise.csv",#"Folder Path"="https://univlyon2fr.sharepoint.com/sites/datalake_yea/Documents partages/Sources/"]}[Content],
				    #"CSV importé" = Csv.Document(#"d_entreprise csv_https://univlyon2fr sharepoint com/sites/datalake_yea/Documents partages/Sources/",[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(#"CSV importé", [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"id_entreprise", Int64.Type}, {"id_secteur", Int64.Type}, {"nom_entreprise", type text}, {"taille", type text}, {"categorie", type text}, {"siege_social", type text}, {"pays", type text}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

