table D_entreprise
	lineageTag: 64268d34-a21a-4fc2-8013-4564d5251291

	column id_entreprise
		dataType: int64
		formatString: 0
		lineageTag: be531c30-c0a4-4d6d-9b1f-8576d60f18c0
		summarizeBy: none
		sourceColumn: id_entreprise

		annotation SummarizationSetBy = Automatic

	column id_secteur
		dataType: int64
		formatString: 0
		lineageTag: fd6afc1f-7c24-4bc3-9d23-e4f04c95aa27
		summarizeBy: none
		sourceColumn: id_secteur

		annotation SummarizationSetBy = Automatic

	column nom_entreprise
		dataType: string
		lineageTag: bcce51ec-977b-4543-b103-dba7105244f1
		summarizeBy: none
		sourceColumn: nom_entreprise

		annotation SummarizationSetBy = Automatic

	column taille
		dataType: string
		lineageTag: fec3b12a-b778-40c2-b968-a49e1f4e93a3
		summarizeBy: none
		sourceColumn: taille

		annotation SummarizationSetBy = Automatic

	column categorie
		dataType: string
		lineageTag: 0a77be9d-274d-4cfc-a806-39992f67df8d
		summarizeBy: none
		sourceColumn: categorie

		annotation SummarizationSetBy = Automatic

	column siege_social
		dataType: string
		lineageTag: 5d17a537-8fe2-4745-8b5c-42651036700e
		summarizeBy: none
		sourceColumn: siege_social

		annotation SummarizationSetBy = Automatic

	column pays
		dataType: string
		lineageTag: 8da0c78e-bd27-43ce-b9b4-d16f01c998b6
		summarizeBy: none
		sourceColumn: pays

		annotation SummarizationSetBy = Automatic

	column NoteMoyenneEntreprise = ```
			
			AVERAGEX(
			    RELATEDTABLE(D_note),
			    D_note[note]
			)
			
			```
		lineageTag: 47bec14c-1701-46c0-b3f7-f00fef22236b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NoteMoyenneSecteur = ```
			
			VAR secteur = D_entreprise[id_secteur]   
			RETURN
			CALCULATE(
			    AVERAGE(D_note[note]),
			    FILTER(
			        F_avis,
			        RELATED(D_entreprise[id_secteur]) = secteur   -- on compare le secteur du fait avec la variable
			    )
			)
			
			
			
			```
		lineageTag: 14b65e84-b79e-4f00-bda4-97c06be35c0c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Note = ```
			
			COALESCE(
			    D_entreprise[NoteMoyenneEntreprise],   -- si la note moyenne existe, on la garde
			    D_entreprise[NoteMoyenneSecteur]       -- sinon on prend la moyenne du secteur
			)
			
			```
		lineageTag: 60b08795-67d9-482c-baa4-45b2485c6de8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Arrondi_note = ROUND(D_entreprise[Note],0)
		lineageTag: db8756db-cb6a-4821-b10e-637deea0bb39
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Etoiles = ```
			
			SWITCH(
			    TRUE(),
			    D_entreprise[arrondi_note] = 5, "⭐⭐⭐⭐⭐",
			    D_entreprise[arrondi_note] = 4, "⭐⭐⭐⭐",
			    D_entreprise[arrondi_note] = 3, "⭐⭐⭐",
			    D_entreprise[arrondi_note] = 2, "⭐⭐",
			    D_entreprise[arrondi_note] = 1, "⭐",
			    ""   -- valeur par défaut si arrondi_note est vide ou autre
			)
			
			```
		lineageTag: 37950631-f1ec-4b31-9829-a9eff839000f
		summarizeBy: none
		sortByColumn: Arrondi_note

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition D_entreprise = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://univlyon2fr.sharepoint.com/sites/datalake_yea", [ApiVersion = 15]),
				    #"d_entreprise csv_https://univlyon2fr sharepoint com/sites/datalake_yea/Documents partages/Sources/" = Source{[Name="d_entreprise.csv",#"Folder Path"="https://univlyon2fr.sharepoint.com/sites/datalake_yea/Documents partages/Sources/"]}[Content],
				    #"CSV importé" = Csv.Document(#"d_entreprise csv_https://univlyon2fr sharepoint com/sites/datalake_yea/Documents partages/Sources/",[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(#"CSV importé", [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"id_entreprise", Int64.Type}, {"id_secteur", Int64.Type}, {"nom_entreprise", type text}, {"taille", type text}, {"categorie", type text}, {"siege_social", type text}, {"pays", type text}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

