table D_ville
	lineageTag: 464e3374-33d1-4980-a0ab-b42541ac15a0

	column id_ville
		dataType: int64
		formatString: 0
		lineageTag: ddc16691-5f05-4cb2-936a-5971959e0425
		summarizeBy: none
		sourceColumn: id_ville

		annotation SummarizationSetBy = Automatic

	column ville
		dataType: string
		lineageTag: 29cb47f7-4445-43c3-8bf1-badb10486337
		summarizeBy: none
		sourceColumn: ville

		annotation SummarizationSetBy = Automatic

	column pays
		dataType: string
		lineageTag: 0d11dcf3-79d1-4e0b-8772-61dfe4ce54e0
		summarizeBy: none
		sourceColumn: pays

		annotation SummarizationSetBy = Automatic

	partition D_ville = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://univlyon2fr.sharepoint.com/sites/datalake_yea", [ApiVersion = 15]),
				    #"d_ville csv_https://univlyon2fr sharepoint com/sites/datalake_yea/Documents partages/Sources/" = Source{[Name="d_ville.csv",#"Folder Path"="https://univlyon2fr.sharepoint.com/sites/datalake_yea/Documents partages/Sources/"]}[Content],
				    #"CSV importé" = Csv.Document(#"d_ville csv_https://univlyon2fr sharepoint com/sites/datalake_yea/Documents partages/Sources/",[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(#"CSV importé", [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"id_ville", Int64.Type}, {"ville", type text}, {"pays", type text}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

