table F_avis
	lineageTag: 4a99429f-4443-4bbe-b6d0-4101ee953e65

	column id_avis
		dataType: int64
		formatString: 0
		lineageTag: 4b8d711d-aad7-47a5-8ac7-9c10933adcc7
		summarizeBy: sum
		sourceColumn: id_avis

		annotation SummarizationSetBy = Automatic

	column id_note
		dataType: int64
		formatString: 0
		lineageTag: 096b3368-d638-4a22-b185-4ba31d09e633
		summarizeBy: none
		sourceColumn: id_note

		annotation SummarizationSetBy = Automatic

	column date_publication
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1e056e65-21e7-47e6-b701-74b63db84497
		summarizeBy: none
		sourceColumn: date_publication

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column contenu_avis
		dataType: string
		lineageTag: e5e335f1-09de-4dba-95f0-8f5a02b0f084
		summarizeBy: none
		sourceColumn: contenu_avis

		annotation SummarizationSetBy = Automatic

	column inconvenient
		dataType: string
		lineageTag: 19e5db44-46de-4f8a-8b2a-65e1d492cf08
		summarizeBy: none
		sourceColumn: inconvenient

		annotation SummarizationSetBy = Automatic

	column avantage
		dataType: string
		lineageTag: 9a427974-8da8-48b2-a838-fdc9c50894fd
		summarizeBy: none
		sourceColumn: avantage

		annotation SummarizationSetBy = Automatic

	column id_entreprise
		dataType: int64
		formatString: 0
		lineageTag: 6ea1fe79-d5dd-45aa-a7e5-bd65b0e9eaee
		summarizeBy: none
		sourceColumn: id_entreprise

		annotation SummarizationSetBy = Automatic

	partition F_avis = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://univlyon2fr.sharepoint.com/sites/datalake_yea", [ApiVersion = 15]),
				    #"F_avis csv_https://univlyon2fr sharepoint com/sites/datalake_yea/Documents partages/Sources/" = Source{[Name="F_avis.csv",#"Folder Path"="https://univlyon2fr.sharepoint.com/sites/datalake_yea/Documents partages/Sources/"]}[Content],
				    #"CSV importé" = Csv.Document(#"F_avis csv_https://univlyon2fr sharepoint com/sites/datalake_yea/Documents partages/Sources/",[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(#"CSV importé", [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"id_avis", Int64.Type}, {"id_note", Int64.Type}, {"date_publication", type date}, {"contenu_avis", type text}, {"inconvenient", type text}, {"avantage", type text}, {"id_entreprise", Int64.Type}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

