table F_offres
	lineageTag: 94be368d-5f6d-4705-849d-3ba2444f315d

	column id_offre
		dataType: int64
		formatString: 0
		lineageTag: 6912a871-9d65-46bc-88eb-a82558d9480b
		summarizeBy: sum
		sourceColumn: id_offre

		annotation SummarizationSetBy = Automatic

	column id_entreprise
		dataType: int64
		formatString: 0
		lineageTag: bfbe34c0-9681-4da4-ada7-81127475be08
		summarizeBy: none
		sourceColumn: id_entreprise

		annotation SummarizationSetBy = Automatic

	column id_ville
		dataType: int64
		formatString: 0
		lineageTag: 779f1a06-c01c-472d-9887-122000d92ef5
		summarizeBy: none
		sourceColumn: id_ville

		annotation SummarizationSetBy = Automatic

	column id_type_poste
		dataType: int64
		formatString: 0
		lineageTag: a87f7823-f0c9-472a-bd1e-a06ef7432589
		summarizeBy: none
		sourceColumn: id_type_poste

		annotation SummarizationSetBy = Automatic

	column libelle_emploi
		dataType: string
		lineageTag: ca3f7c7c-2943-4117-a5f4-581c13bbbe0b
		summarizeBy: none
		sourceColumn: libelle_emploi

		annotation SummarizationSetBy = Automatic

	column contenu
		dataType: string
		lineageTag: ece1bdbd-501b-43d9-88e7-47fe484a138e
		summarizeBy: none
		sourceColumn: contenu

		annotation SummarizationSetBy = Automatic

	column date_posted
		dataType: dateTime
		formatString: Long Date
		lineageTag: 02bc905f-d809-490f-87f2-8e4456e886b4
		summarizeBy: none
		sourceColumn: date_posted

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition F_offres = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://univlyon2fr.sharepoint.com/sites/datalake_yea", [ApiVersion = 15]),
				    #"F_offres csv_https://univlyon2fr sharepoint com/sites/datalake_yea/Documents partages/Sources/" = Source{[Name="F_offres.csv",#"Folder Path"="https://univlyon2fr.sharepoint.com/sites/datalake_yea/Documents partages/Sources/"]}[Content],
				    #"CSV importé" = Csv.Document(#"F_offres csv_https://univlyon2fr sharepoint com/sites/datalake_yea/Documents partages/Sources/",[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(#"CSV importé", [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"id_offre", Int64.Type}, {"id_entreprise", Int64.Type}, {"id_ville", Int64.Type}, {"id_type_poste", Int64.Type}, {"libelle_emploi", type text}, {"contenu", type text}, {"date_posted", type date}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

